# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'KustomerSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KustomerSDK

  pod 'KustomerChat', :git => 'https://github.com/kustomer/kustomer-ios.git'

end
